-- Ajouter les nouvelles valeurs aux enums
ALTER TYPE "ServiceTier" ADD VALUE IF NOT EXISTS 'PROVIDER_FREE';
ALTER TYPE "ServiceTier" ADD VALUE IF NOT EXISTS 'PROVIDER_BASIC';
ALTER TYPE "ServiceTier" ADD VALUE IF NOT EXISTS 'PROVIDER_PRO';
ALTER TYPE "ServiceTier" ADD VALUE IF NOT EXISTS 'PROVIDER_ELITE';

ALTER TYPE "AIRequestType" ADD VALUE IF NOT EXISTS 'IMAGE_ENHANCEMENT';
ALTER TYPE "AIRequestType" ADD VALUE IF NOT EXISTS 'CHAT';

